add apt installation

diff --git a/docker/pkg/Dockerfile.ubuntu b/docker/pkg/Dockerfile.ubuntu
--- a/docker/pkg/Dockerfile.ubuntu
+++ b/docker/pkg/Dockerfile.ubuntu
@@ -13,9 +13,17 @@ RUN apt-get install software-properties-common -y \
     && add-apt-repository -y universe 
 
 RUN apt-get update && apt-get install -y curl \
-    && VERSION=$(curl -s https://api.github.com/repos/ros-infrastructure/ros-apt-source/releases/latest | grep -F "tag_name" | awk -F'"' '{print $4}') \
+    && ROS_APT_SOURCE_VERSION=$(curl -s https://api.github.com/repos/ros-infrastructure/ros-apt-source/releases/latest | grep -F "tag_name" | awk -F'"' '{print $4}') \
     && UBUNTU_CODE=$(. /etc/os-release && echo ${UBUNTU_CODENAME:-${VERSION_CODENAME}}) \
-    && curl -L -o /tmp/ros2-apt-source.deb "https://github.com/ros-infrastructure/ros-apt-source/releases/download/${VERSION}/ros2-apt-source_${VERSION}.${UBUNTU_CODE}_all.deb" \
+    && curl -L -o /tmp/ros2-apt-source.deb "https://github.com/ros-infrastructure/ros-apt-source/releases/download/${ROS_APT_SOURCE_VERSION}/ros2-apt-source_${ROS_APT_SOURCE_VERSION}.${UBUNTU_CODE}_all.deb" \
     && dpkg -i /tmp/ros2-apt-source.deb \
-    || (echo "Download failed. Check if version $VERSION exists for $UBUNTU_CODE" && exit 1) \
+    || (echo "Download failed. Check if version $ROS_APT_SOURCE_VERSION exists for $UBUNTU_CODE" && exit 1) \
     && rm /tmp/ros2-apt-source.deb
+
+RUN apt update && sudo apt install ros-dev-tools \
+    && apt update && apt upgrade -y \
+    && apt install ros-${ROS2_VERSION}-desktop -y
+
+RUN echo "source /opt/ros/${ROS2_VERSION}/setup.bash" >> ~/.bashrc
+
+CMD ["/bin/bash"]
